apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout.fullname" . }}
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blockscout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blockscout.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blockscout.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: check-db-ready
        image: docker.io/bitnami/postgresql:11.13.0-debian-10-r60
        command: ['sh', '-c', 
          'until pg_isready -h {{ .Release.Name }}-postgresql.{{.Release.Namespace }} -p 5432 -U postgres; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["mix do ecto.create, ecto.migrate; mix phx.server"]
          ports:
            - name: blockscout
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: blockscout
          readinessProbe:
            httpGet:
              path: /
              port: blockscout
          env:
            {{ with .Values.extraEnv -}}
            {{ tpl . $ | indent 12 }}
            {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
